### ISSUE TITLE
doctests not supported 

### ISSUE THREAD

**Issue by marscher** [adamchainz/pytest-randomly#30]
If doctests are enabled the following exception is raised:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/marscher/miniconda3/lib/python3.5/site-packages/_pytest/main.py", line 96, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/marscher/miniconda3/lib/python3.5/site-packages/_pytest/main.py", line 130, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/marscher/miniconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/marscher/miniconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/marscher/miniconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/marscher/miniconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/marscher/miniconda3/lib/python3.5/site-packages/_pytest/main.py", line 139, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/home/marscher/miniconda3/lib/python3.5/site-packages/_pytest/main.py", line 592, in perform_collect
INTERNALERROR>     config=self.config, items=items)
INTERNALERROR>   File "/home/marscher/miniconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/marscher/miniconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/marscher/miniconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/marscher/miniconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/marscher/miniconda3/lib/python3.5/site-packages/pytest_randomly.py", line 125, in pytest_collection_modifyitems
INTERNALERROR>     current_module = item.module
INTERNALERROR> AttributeError: 'DoctestItem' object has no attribute 'module'
```

**Comment by marscher** [comment]
The necessary condition is only to have doctests contained in the test-paths.

**Comment by adamchainz** [comment]
Ah, so `pytest-randomly` currently assumes that tests have a module, which works with doctests inside code ( e.g. https://github.com/adamchainz/pytest-randomly/blob/master/tests/test_it.py#L264 ) but it doesn't with your doctests. I'm guessing yours are in a restructured text file?

**Comment by adamchainz** [comment]
You know you can... make a PR 😄

**Comment by marscher** [comment]
No the test is also contained in a py module.

**Comment by adamchainz** [comment]
Oh, how weird. If you can replicate it with a test in this suite then we'll have something to work with

**Comment by adamchainz** [comment]
I just tried doctests in txt files in #41 just in case they came in with no `module` attribute, but they still worked. Since there's been no more info since October I'm going to close this. If you can come back with more info @marscher please feel free to reopen.
